version: '2'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  scheduler:
    image: flum1025/tweam
    volumes:
      - setting.yml:/setting.yml
    command: scheduler -config /setting.yml
  worker:
    image: flum1025/tweam
    volumes:
      - setting.yml:/setting.yml
    command: worker -config /setting.yml
